package com.healthgov.dto;

import java.time.LocalDate;
import java.util.Date;
import lombok.Data;

@Data
public class EnrollmentDTO {
    private Long enrollmentId;  // generated by DB; omit on POST
    private Long citizenId;     // required
    private Long programId;     // required
    private LocalDate date;          // java.util.Date
    private String status;
}