package com.healthgov.dto;

import java.sql.Date;

import com.healthgov.enums.ProgramStatus;

import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import lombok.Data;

@Data
public class HealthProgramDTO {
      // generated by DB; omit on POST
	private Long programId;
    private String title;
    private String description;
    private Date startDate;   // java.sql.Date
    private Date endDate;     // java.sql.Date
    private Double budget;
    @Enumerated(EnumType.STRING)
    private ProgramStatus status;
}